# This file is generated by coder.py. DO NOT EDIT!
# ruff: noqa: F401, E402, F811
# fmt: off

from __future__ import annotations

import enum

from gaphor.core.modeling.properties import (
    association,
    attribute as _attribute,
    derived,
    derivedunion,
    enumeration as _enumeration,
    redefine,
    relation_many,
    relation_one,
)


from gaphor.core.modeling.base import Base as _Base


class FeatureDirectionKind(enum.StrEnum):
    in_ = "in"
    inout = "inout"
    out = "out"


class VisibilityKind(enum.StrEnum):
    private = "private"
    protected = "protected"
    public = "public"


class Element(_Base):
    aliasIds: _attribute[str] = _attribute("aliasIds", str)
    declaredName: _attribute[str] = _attribute("declaredName", str)
    declaredShortName: _attribute[str] = _attribute("declaredShortName", str)
    elementId: _attribute[str] = _attribute("elementId", str)
    isImpliedIncluded: _attribute[bool] = _attribute("isImpliedIncluded", bool)
    ownedRelationship: relation_many[Relationship]
    owningRelationship: relation_many[Relationship]


class AnnotatingElement(Element):
    pass


class Namespace(Element):
    pass


class Type(Namespace):
    isAbstract: _attribute[bool] = _attribute("isAbstract", bool)
    isSufficient: _attribute[bool] = _attribute("isSufficient", bool)


class Classifier(Type):
    pass


class Relationship(Element):
    isImplied: _attribute[bool] = _attribute("isImplied", bool)
    ownedRelatedElement: relation_many[Element]
    owningRelatedElement: relation_many[Element]
    source: relation_many[Element]
    target: relation_many[Element]


class Association(Classifier, Relationship):
    pass


class Class(Classifier):
    pass


class Structure(Class):
    pass


class AssociationStructure(Association, Structure):
    pass


class Behavior(Class):
    pass


class Feature(Type):
    direction = _enumeration("direction", FeatureDirectionKind, None)
    isComposite: _attribute[bool] = _attribute("isComposite", bool)
    isConstant: _attribute[bool] = _attribute("isConstant", bool)
    isDerived: _attribute[bool] = _attribute("isDerived", bool)
    isEnd: _attribute[bool] = _attribute("isEnd", bool)
    isOrdered: _attribute[bool] = _attribute("isOrdered", bool)
    isPortion: _attribute[bool] = _attribute("isPortion", bool)
    isUnique: _attribute[bool] = _attribute("isUnique", bool)
    isVariable: _attribute[bool] = _attribute("isVariable", bool)


class Step(Feature):
    pass


class Expression(Step):
    pass


class BooleanExpression(Expression):
    pass


class Comment(AnnotatingElement):
    body: _attribute[str] = _attribute("body", str)
    locale: _attribute[str] = _attribute("locale", str)


class Conjugation(Relationship):
    conjugatedType: relation_many[Type]
    originalType: relation_many[Type]


class Connector(Feature, Relationship):
    pass


class DataType(Classifier):
    pass


class Documentation(Comment):
    pass


class Membership(Relationship):
    memberElement: relation_many[Element]
    memberName: _attribute[str] = _attribute("memberName", str)
    memberShortName: _attribute[str] = _attribute("memberShortName", str)
    visibility = _enumeration("visibility", VisibilityKind, VisibilityKind.private)


class OwningMembership(Membership):
    pass


class FeatureMembership(OwningMembership):
    pass


class Specialization(Relationship):
    general: relation_many[Type]
    specific: relation_many[Type]


class FeatureTyping(Specialization):
    type: relation_many[Type]
    typedFeature: relation_many[Feature]


class Flow(Connector, Step):
    pass


class Function(Behavior):
    pass


class Import(Relationship):
    isImportAll: _attribute[bool] = _attribute("isImportAll", bool)
    isRecursive: _attribute[bool] = _attribute("isRecursive", bool)
    visibility = _enumeration("visibility", VisibilityKind, VisibilityKind.private)


class Package(Namespace):
    pass


class ParameterMembership(FeatureMembership):
    pass


class Predicate(Function):
    pass


class Subsetting(Specialization):
    subsettedFeature: relation_many[Feature]
    subsettingFeature: relation_many[Feature]


class Redefinition(Subsetting):
    redefinedFeature: relation_many[Feature]
    redefiningFeature: relation_many[Feature]


class ReferenceSubsetting(Subsetting):
    referencedFeature: relation_many[Feature]


class Subclassification(Specialization):
    subclassifier: relation_many[Classifier]
    superclassifier: relation_many[Classifier]


class Succession(Connector):
    pass


class TextualRepresentation(AnnotatingElement):
    body: _attribute[str] = _attribute("body", str)
    language: _attribute[str] = _attribute("language", str)



Element.owningRelationship = association("owningRelationship", Relationship)
Element.ownedRelationship = association("ownedRelationship", Relationship, composite=True)
Relationship.target = association("target", Element)
Relationship.source = association("source", Element)
Relationship.owningRelatedElement = association("owningRelatedElement", Element)
Relationship.ownedRelatedElement = association("ownedRelatedElement", Element, composite=True)
Conjugation.originalType = association("originalType", Type)
Conjugation.conjugatedType = association("conjugatedType", Type)
Membership.memberElement = association("memberElement", Element)
Specialization.general = association("general", Type)
Specialization.specific = association("specific", Type)
FeatureTyping.typedFeature = association("typedFeature", Feature)
FeatureTyping.type = association("type", Type)
Subsetting.subsettedFeature = association("subsettedFeature", Feature)
Subsetting.subsettingFeature = association("subsettingFeature", Feature)
Redefinition.redefiningFeature = association("redefiningFeature", Feature)
Redefinition.redefinedFeature = association("redefinedFeature", Feature)
ReferenceSubsetting.referencedFeature = association("referencedFeature", Feature)
Subclassification.superclassifier = association("superclassifier", Classifier)
Subclassification.subclassifier = association("subclassifier", Classifier)
