# This file is generated by coder.py. DO NOT EDIT!
# ruff: noqa: F401, E402, F811
# fmt: off

from __future__ import annotations

import enum

from gaphor.core.modeling.properties import (
    association,
    attribute as _attribute,
    derived,
    derivedunion,
    enumeration as _enumeration,
    redefine,
    relation_many,
    relation_one,
)


from gaphor.core.modeling.base import Base as _Base


class Element(_Base):
    declaredName: _attribute[str] = _attribute("declaredName", str)
    isLibraryElement: _attribute[bool] = _attribute("isLibraryElement", bool)
    ownedElement: relation_many[Element]



Element.ownedElement = association("ownedElement", Element, composite=True)
