# This file is generated by coder.py. DO NOT EDIT!
# ruff: noqa: F401, E402, F811
# fmt: off

from __future__ import annotations

import enum

from gaphor.core.modeling.properties import (
    association,
    attribute as _attribute,
    derived,
    derivedunion,
    enumeration as _enumeration,
    redefine,
    relation_many,
    relation_one,
)


from gaphor.core.modeling.base import Base as _Base
from gaphor.SysML2.kerml import Class as _Class
from gaphor.SysML2.kerml import Classifier as _Classifier
from gaphor.SysML2.kerml import Feature as _Feature
from gaphor.SysML2.kerml import Structure as _Structure


class PortionKind(enum.StrEnum):
    timeslice = "timeslice"
    snapshot = "snapshot"


class Definition(_Classifier):
    isVariation: _attribute[bool] = _attribute("isVariation", bool)


class OccurrenceDefinition(Definition, _Class):
    isIndividual: _attribute[bool] = _attribute("isIndividual", bool)


class ItemDefinition(OccurrenceDefinition, _Structure):
    pass


class Usage(_Feature):
    isVariation: _attribute[bool] = _attribute("isVariation", bool)


class OccurrenceUsage(Usage):
    isIndividual: _attribute[bool] = _attribute("isIndividual", bool)
    portionKind = _enumeration("portionKind", PortionKind, PortionKind.timeslice)


class ItemUsage(OccurrenceUsage):
    pass


class PartDefinition(ItemDefinition):
    pass


class PartUsage(ItemUsage):
    pass



