# This file is generated by coder.py. DO NOT EDIT!
# ruff: noqa: F401, E402, F811
# fmt: off

from __future__ import annotations

import enum

from gaphor.core.modeling.properties import (
    association,
    attribute as _attribute,
    derived,
    derivedunion,
    enumeration as _enumeration,
    redefine,
    relation_many,
    relation_one,
)


from gaphor.core.modeling.base import Base as _Base
from gaphor.SysML2.kerml import AssociationStructure as _AssociationStructure
from gaphor.SysML2.kerml import Behavior as _Behavior
from gaphor.SysML2.kerml import BooleanExpression as _BooleanExpression
from gaphor.SysML2.kerml import Class as _Class
from gaphor.SysML2.kerml import Classifier as _Classifier
from gaphor.SysML2.kerml import Conjugation as _Conjugation
from gaphor.SysML2.kerml import Connector as _Connector
from gaphor.SysML2.kerml import DataType as _DataType
from gaphor.SysML2.kerml import Feature as _Feature
from gaphor.SysML2.kerml import FeatureMembership as _FeatureMembership
from gaphor.SysML2.kerml import FeatureTyping as _FeatureTyping
from gaphor.SysML2.kerml import ParameterMembership as _ParameterMembership
from gaphor.SysML2.kerml import Predicate as _Predicate
from gaphor.SysML2.kerml import Step as _Step
from gaphor.SysML2.kerml import Structure as _Structure


class PortionKind(enum.StrEnum):
    timeslice = "timeslice"
    snapshot = "snapshot"


class RequirementConstraintKind(enum.StrEnum):
    assumption = "assumption"
    requirement = "requirement"


class Definition(_Classifier):
    isVariation: _attribute[bool] = _attribute("isVariation", bool)


class OccurrenceDefinition(Definition, _Class):
    isIndividual: _attribute[bool] = _attribute("isIndividual", bool)


class ActionDefinition(OccurrenceDefinition, _Behavior):
    pass


class Usage(_Feature):
    isVariation: _attribute[bool] = _attribute("isVariation", bool)


class OccurrenceUsage(Usage):
    isIndividual: _attribute[bool] = _attribute("isIndividual", bool)
    portionKind = _enumeration("portionKind", PortionKind, None)


class ActionUsage(OccurrenceUsage, _Step):
    pass


class ActorMembership(_ParameterMembership):
    pass


class AttributeDefinition(Definition, _DataType):
    pass


class AttributeUsage(Usage):
    pass


class ConstraintDefinition(OccurrenceDefinition, _Predicate):
    pass


class RequirementDefinition(ConstraintDefinition):
    reqId: _attribute[str] = _attribute("reqId", str)


class ConcernDefinition(RequirementDefinition):
    pass


class ConstraintUsage(OccurrenceUsage, _BooleanExpression):
    pass


class RequirementUsage(ConstraintUsage):
    reqId: _attribute[str] = _attribute("reqId", str)


class ConcernUsage(RequirementUsage):
    pass


class PortDefinition(OccurrenceDefinition, _Structure):
    pass


class ConjugatedPortDefinition(PortDefinition):
    pass


class ConjugatedPortTyping(_FeatureTyping):
    conjugatedPortDefinition: relation_many[ConjugatedPortDefinition]


class ItemDefinition(OccurrenceDefinition, _Structure):
    pass


class PartDefinition(ItemDefinition):
    pass


class ConnectionDefinition(PartDefinition, _AssociationStructure):
    isSufficient: _attribute[bool] = _attribute("isSufficient", bool)


class ItemUsage(OccurrenceUsage):
    pass


class PartUsage(ItemUsage):
    pass


class ConnectorAsUsage(Usage, _Connector):
    pass


class ConnectionUsage(ConnectorAsUsage, PartUsage):
    pass


class RequirementConstraintMembership(_FeatureMembership):
    kind = _enumeration("kind", RequirementConstraintKind, RequirementConstraintKind.assumption)


class FramedConcernMembership(RequirementConstraintMembership):
    kind = _enumeration("kind", RequirementConstraintKind, RequirementConstraintKind.assumption)


class InterfaceDefinition(ConnectionDefinition):
    pass


class InterfaceUsage(ConnectionUsage):
    pass


class PortConjugation(_Conjugation):
    originalPortDefinition: relation_many[PortDefinition]


class PortUsage(OccurrenceUsage):
    pass


class StakeholderMembership(_ParameterMembership):
    pass


class SubjectMembership(_ParameterMembership):
    pass



ConjugatedPortTyping.conjugatedPortDefinition = association("conjugatedPortDefinition", ConjugatedPortDefinition)
PortConjugation.originalPortDefinition = association("originalPortDefinition", PortDefinition)
